spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/registry?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=America/Los_Angeles
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

registry:
  file:
    dir: /data/applogs/registry/registrydata

server:
  port: 8080